---
- name: Pull OP-Batcher image
  become: true
  docker_image:
    name: "{{ opbatcher_docker_image }}"
    source: pull
    
- name: Start OP-Batcher container
  become: true
  ansible.builtin.docker_container:
    name: "{{ opbatcher_node_name }}"
    hostname: "{{ opbatcher_node_name }}"
    image: "{{ opbatcher_docker_image }}"
    entrypoint:
      - op-batcher
      - --l2-eth-rpc=http://op-geth:8545
      - --rollup-rpc=http://op-node:8547
      - --poll-interval=1s
      - --sub-safety-margin=6
      - --num-confirmations=1
      - --safe-abort-nonce-too-low-count=3
      - --resubmission-timeout=30s
      - --rpc.addr=0.0.0.0
      - --rpc.port={{ opbatcher_rpc_port}}
      - --rpc.enable-admin
      - --max-channel-duration=1
      - --l1-eth-rpc={{ L1_RPC_URL }}
      - --private-key={{ GS_BATCHER_PRIVATE_KEY }}
      - --metrics.enabled=true
      - --metrics.addr=0.0.0.0
      - --metrics.port={{ opbatcher_metrics_port }}
    state: started
    restart_policy: always
    networks_cli_compatible: yes
    networks:
      - name: "{{ docker_network_name }}"
    ports: "{{ opbatcher_ports }}"
    volumes:
      - "{{ opbatcher_appdata }}/data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

- name: Pause ansible task for 10 seconds so that OP-Batcher container will be up and running
  pause:
    seconds: 10
