---
- name: Pull OP-Proposer image
  become: true
  docker_image:
    name: "{{ opproposer_docker_image }}"
    source: pull

- name: Start OP-Proposer container
  become: true
  ansible.builtin.docker_container:
    name: "{{ opproposer_node_name }}"
    hostname: "{{ opproposer_node_name }}"
    image: "{{ opproposer_docker_image }}"
    entrypoint:
      - op-proposer
      - --poll-interval=12s
      - --rpc.port={{ oppropose_rpc_port }}
      - --rollup-rpc=http://op-node:8547
      - --l2oo-address={{ L2_OUTPUT_ORACLE_PROXY_ADDRESS }}
      - --private-key={{ GS_PROPOSER_PRIVATE_KEY }}
      - --l1-eth-rpc={{ L1_RPC_URL }}
      - --metrics.enabled=true
      - --metrics.addr=0.0.0.0
      - --metrics.port={{ oppropose_metrics_port }}
    state: started
    restart_policy: always
    networks_cli_compatible: yes
    networks:
      - name: "{{ docker_network_name }}"
    ports: "{{ oppropose_ports }}"
    volumes:
      - "{{ opproposer_appdata }}/data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

